// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///
///
///
///
///
///
/// import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart';
//
// // ...
//
// await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
// );
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2NTTIUeK233ucaazH0Ju4tS-BlqnAP5E',
    appId: '1:1037178946224:web:7e86a251e78cc885d2b175',
    messagingSenderId: '1037178946224',
    projectId: 'kriti-backend-2',
    authDomain: 'kriti-backend-2.firebaseapp.com',
    storageBucket: 'kriti-backend-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4ttBSlCEDROq39Ama3rYHTA4L6-GA4cg',
    appId: '1:1037178946224:android:b8e94c72fa3c6b69d2b175',
    messagingSenderId: '1037178946224',
    projectId: 'kriti-backend-2',
    storageBucket: 'kriti-backend-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF4tKblDIp2iafBF3wLsxGf3QxTFZyjV4',
    appId: '1:1037178946224:ios:6c3ee95c250fd4a2d2b175',
    messagingSenderId: '1037178946224',
    projectId: 'kriti-backend-2',
    storageBucket: 'kriti-backend-2.appspot.com',
    iosBundleId: 'com.example.kriiti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF4tKblDIp2iafBF3wLsxGf3QxTFZyjV4',
    appId: '1:1037178946224:ios:f883735e06728775d2b175',
    messagingSenderId: '1037178946224',
    projectId: 'kriti-backend-2',
    storageBucket: 'kriti-backend-2.appspot.com',
    iosBundleId: 'com.example.kriiti.RunnerTests',
  );
}
